# netlify.toml

[build]
  command = "npm run build"    # Adjust the build command as per your project setup

[[redirects]]
  from = "/api/*"
  to = "https://propertyportalbackend-0mn7.onrender.com/:splat"
  status = 200
  force = true

